#! /bin/zsh

# Helps mounting Ubuntu on /mnt from Debian.

sudo mount /dev/nvme0n1p3 /mnt
sudo mount -t proc proc /mnt/proc
sudo mount -t sysfs sys /mnt/sys
sudo mount -o bind /dev /mnt/dev
sudo mount /dev/nvme0n1p7 /mnt/home/
sudo rm /mnt/etc/resolv.conf
sudo cp /etc/resolv.conf /mnt/etc/resolv.conf
